// auth
const LOGIN = {
  LOAD: "LOAD_LOGIN",
  SUCCESS: "SUCCESS_LOGIN",
  FAIL: "FAIL_LOGIN",
};

// user
const ADD_USER = {
  LOAD: "LOAD_ADD_USER",
  SUCCESS: "SUCCESS_ADD_USER",
  FAIL: "FAIL_ADD_USER",
};

const GET_USER = {
  LOAD: "LOAD_GET_USER",
  SUCCESS: "SUCCESS_GET_USER",
  FAIL: "FAIL_GET_USER",
};

const UPDATE_USER = {
  LOAD: "LOAD_UPDATE_USER",
  SUCCESS: "SUCCESS_UPDATE_USER",
  FAIL: "FAIL_UPDATE_USER",
};

const DELETE_USER = {
  LOAD: "LOAD_DELETE_USER",
  SUCCESS: "SUCCESS_DELETE_USER",
  FAIL: "FAIL_DELETE_USER",
};

// todo
const ADD_TODO = {
  LOAD: "LOAD_ADD_TODO",
  SUCCESS: "SUCCESS_ADD_TODO",
  FAIL: "FAIL_ADD_TODO",
};

const LIST_TODO = {
  LOAD: "LOAD_TODO_LIST",
  SUCCESS: "SUCCESS_TODO_LIST",
  FAIL: "FAIL_TODO_LIST",
};

const UPDATE_TODO = {
  LOAD: "LOAD_UPDATE_TODO",
  SUCCESS: "SUCCESS_UPDATE_TODO",
  FAIL: "FAIL_UPDATE_TODO",
};

const DELETE_TODO = {
  LOAD: "LOAD_DELETE_TODO",
  SUCCESS: "SUCCESS_DELETE_TODO",
  FAIL: "FAIL_DELETE_TODO",
};

export {
  LOGIN,
  ADD_USER,
  GET_USER,
  UPDATE_USER,
  DELETE_USER,
  ADD_TODO,
  LIST_TODO,
  UPDATE_TODO,
  DELETE_TODO,
};
